---
title: "index.rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exploratory Analysis

### Introduction 

This is the start of the introduction! Paste the neccessary information from
the project proposal!!


### Summary Information

### Table of aggregated data? do we even have to put this one here? check

### First Chart

```{r, echo = FALSE, include = F, warning = FALSE}
library(ggplot2)
library(dplyr)
library(tidyverse)
# Histogram of Mental Health Ratings/Amount of Responses separated by Gender----

dataset <- read.csv("https://query.data.world/s/x7qrjzoufcjzx6agzg5d6omncpzup7", header=TRUE, stringsAsFactors=FALSE)
colnames(dataset)
names(dataset)[names(dataset) == "PHYS8"] <- "how would you rate your health"
names(dataset)[names(dataset) == "GENDER"] <- "gender"

dataset2 <- dataset %>%  select(`how would you rate your health`, gender)
```
```{r, echo =FALSE, warning = FALSE}

# Start of the histogram (run everything before in the right order first)

dataset3 <- dataset2 %>%
  select(`how would you rate your health`, gender) %>%
  filter(`how would you rate your health` != "(98) SKIPPED ON WEB") %>%
  filter(gender != "(98) SKIPPED ON WEB") %>%
  filter(`how would you rate your health` != "(77) DON'T KNOW")

dataset3$`how would you rate your health` <- as.character(dataset3$`how would you rate your health`)
dataset3[dataset3 == "(1) Excellent"] <- "Excellent"
dataset3[dataset3 == "(2) Very good"] <- "Very Good"
dataset3[dataset3 == "(3) Good"] <- "Good"
dataset3[dataset3 == "(4) Fair"] <- "Fair"
dataset3[dataset3 == "(5) Poor"] <- "Poor"
dataset3$`how would you rate your health` <- as.factor(dataset3$`how would you rate your health`)

names(dataset3)[names(dataset3) == "how would you rate your health"] <- "Mental Health Rating"

ggplot(data = dataset3, mapping = aes(x = `Mental Health Rating`, fill = `Mental Health Rating`)) + 
  geom_histogram(binwidth = 1, stat = "count") +
  labs(x = "Level of Mental Health", y = "Amount of Responses") +
  facet_wrap(~gender, labeller = "label_both") 
```

### Second Chart!


### Third Chart
